# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fan/code/kiscript_water_version

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fan/code/kiscript_water_version

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fan/code/kiscript_water_version/CMakeFiles /home/fan/code/kiscript_water_version/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fan/code/kiscript_water_version/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kiscript

# Build rule for target.
kiscript: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kiscript
.PHONY : kiscript

# fast build rule for target.
kiscript/fast:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/build
.PHONY : kiscript/fast

activation_record.o: activation_record.c.o
.PHONY : activation_record.o

# target to build an object file
activation_record.c.o:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/activation_record.c.o
.PHONY : activation_record.c.o

activation_record.i: activation_record.c.i
.PHONY : activation_record.i

# target to preprocess a source file
activation_record.c.i:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/activation_record.c.i
.PHONY : activation_record.c.i

activation_record.s: activation_record.c.s
.PHONY : activation_record.s

# target to generate assembly for a file
activation_record.c.s:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/activation_record.c.s
.PHONY : activation_record.c.s

expression_parser.o: expression_parser.c.o
.PHONY : expression_parser.o

# target to build an object file
expression_parser.c.o:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/expression_parser.c.o
.PHONY : expression_parser.c.o

expression_parser.i: expression_parser.c.i
.PHONY : expression_parser.i

# target to preprocess a source file
expression_parser.c.i:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/expression_parser.c.i
.PHONY : expression_parser.c.i

expression_parser.s: expression_parser.c.s
.PHONY : expression_parser.s

# target to generate assembly for a file
expression_parser.c.s:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/expression_parser.c.s
.PHONY : expression_parser.c.s

function_parser.o: function_parser.c.o
.PHONY : function_parser.o

# target to build an object file
function_parser.c.o:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/function_parser.c.o
.PHONY : function_parser.c.o

function_parser.i: function_parser.c.i
.PHONY : function_parser.i

# target to preprocess a source file
function_parser.c.i:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/function_parser.c.i
.PHONY : function_parser.c.i

function_parser.s: function_parser.c.s
.PHONY : function_parser.s

# target to generate assembly for a file
function_parser.c.s:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/function_parser.c.s
.PHONY : function_parser.c.s

glib_utils.o: glib_utils.c.o
.PHONY : glib_utils.o

# target to build an object file
glib_utils.c.o:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/glib_utils.c.o
.PHONY : glib_utils.c.o

glib_utils.i: glib_utils.c.i
.PHONY : glib_utils.i

# target to preprocess a source file
glib_utils.c.i:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/glib_utils.c.i
.PHONY : glib_utils.c.i

glib_utils.s: glib_utils.c.s
.PHONY : glib_utils.s

# target to generate assembly for a file
glib_utils.c.s:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/glib_utils.c.s
.PHONY : glib_utils.c.s

interpreter.o: interpreter.c.o
.PHONY : interpreter.o

# target to build an object file
interpreter.c.o:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/interpreter.c.o
.PHONY : interpreter.c.o

interpreter.i: interpreter.c.i
.PHONY : interpreter.i

# target to preprocess a source file
interpreter.c.i:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/interpreter.c.i
.PHONY : interpreter.c.i

interpreter.s: interpreter.c.s
.PHONY : interpreter.s

# target to generate assembly for a file
interpreter.c.s:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/interpreter.c.s
.PHONY : interpreter.c.s

lexical_parser.o: lexical_parser.c.o
.PHONY : lexical_parser.o

# target to build an object file
lexical_parser.c.o:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/lexical_parser.c.o
.PHONY : lexical_parser.c.o

lexical_parser.i: lexical_parser.c.i
.PHONY : lexical_parser.i

# target to preprocess a source file
lexical_parser.c.i:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/lexical_parser.c.i
.PHONY : lexical_parser.c.i

lexical_parser.s: lexical_parser.c.s
.PHONY : lexical_parser.s

# target to generate assembly for a file
lexical_parser.c.s:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/lexical_parser.c.s
.PHONY : lexical_parser.c.s

lexical_parser_utils.o: lexical_parser_utils.c.o
.PHONY : lexical_parser_utils.o

# target to build an object file
lexical_parser_utils.c.o:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/lexical_parser_utils.c.o
.PHONY : lexical_parser_utils.c.o

lexical_parser_utils.i: lexical_parser_utils.c.i
.PHONY : lexical_parser_utils.i

# target to preprocess a source file
lexical_parser_utils.c.i:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/lexical_parser_utils.c.i
.PHONY : lexical_parser_utils.c.i

lexical_parser_utils.s: lexical_parser_utils.c.s
.PHONY : lexical_parser_utils.s

# target to generate assembly for a file
lexical_parser_utils.c.s:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/lexical_parser_utils.c.s
.PHONY : lexical_parser_utils.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/main.c.s
.PHONY : main.c.s

module_tests.o: module_tests.c.o
.PHONY : module_tests.o

# target to build an object file
module_tests.c.o:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/module_tests.c.o
.PHONY : module_tests.c.o

module_tests.i: module_tests.c.i
.PHONY : module_tests.i

# target to preprocess a source file
module_tests.c.i:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/module_tests.c.i
.PHONY : module_tests.c.i

module_tests.s: module_tests.c.s
.PHONY : module_tests.s

# target to generate assembly for a file
module_tests.c.s:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/module_tests.c.s
.PHONY : module_tests.c.s

parser.o: parser.c.o
.PHONY : parser.o

# target to build an object file
parser.c.o:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/parser.c.o
.PHONY : parser.c.o

parser.i: parser.c.i
.PHONY : parser.i

# target to preprocess a source file
parser.c.i:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/parser.c.i
.PHONY : parser.c.i

parser.s: parser.c.s
.PHONY : parser.s

# target to generate assembly for a file
parser.c.s:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/parser.c.s
.PHONY : parser.c.s

program_parser.o: program_parser.c.o
.PHONY : program_parser.o

# target to build an object file
program_parser.c.o:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/program_parser.c.o
.PHONY : program_parser.c.o

program_parser.i: program_parser.c.i
.PHONY : program_parser.i

# target to preprocess a source file
program_parser.c.i:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/program_parser.c.i
.PHONY : program_parser.c.i

program_parser.s: program_parser.c.s
.PHONY : program_parser.s

# target to generate assembly for a file
program_parser.c.s:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/program_parser.c.s
.PHONY : program_parser.c.s

statement_parser.o: statement_parser.c.o
.PHONY : statement_parser.o

# target to build an object file
statement_parser.c.o:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/statement_parser.c.o
.PHONY : statement_parser.c.o

statement_parser.i: statement_parser.c.i
.PHONY : statement_parser.i

# target to preprocess a source file
statement_parser.c.i:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/statement_parser.c.i
.PHONY : statement_parser.c.i

statement_parser.s: statement_parser.c.s
.PHONY : statement_parser.s

# target to generate assembly for a file
statement_parser.c.s:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/statement_parser.c.s
.PHONY : statement_parser.c.s

syntactic_parser.o: syntactic_parser.c.o
.PHONY : syntactic_parser.o

# target to build an object file
syntactic_parser.c.o:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/syntactic_parser.c.o
.PHONY : syntactic_parser.c.o

syntactic_parser.i: syntactic_parser.c.i
.PHONY : syntactic_parser.i

# target to preprocess a source file
syntactic_parser.c.i:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/syntactic_parser.c.i
.PHONY : syntactic_parser.c.i

syntactic_parser.s: syntactic_parser.c.s
.PHONY : syntactic_parser.s

# target to generate assembly for a file
syntactic_parser.c.s:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/syntactic_parser.c.s
.PHONY : syntactic_parser.c.s

syntactic_parser_utils.o: syntactic_parser_utils.c.o
.PHONY : syntactic_parser_utils.o

# target to build an object file
syntactic_parser_utils.c.o:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/syntactic_parser_utils.c.o
.PHONY : syntactic_parser_utils.c.o

syntactic_parser_utils.i: syntactic_parser_utils.c.i
.PHONY : syntactic_parser_utils.i

# target to preprocess a source file
syntactic_parser_utils.c.i:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/syntactic_parser_utils.c.i
.PHONY : syntactic_parser_utils.c.i

syntactic_parser_utils.s: syntactic_parser_utils.c.s
.PHONY : syntactic_parser_utils.s

# target to generate assembly for a file
syntactic_parser_utils.c.s:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/syntactic_parser_utils.c.s
.PHONY : syntactic_parser_utils.c.s

utils.o: utils.c.o
.PHONY : utils.o

# target to build an object file
utils.c.o:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/utils.c.o
.PHONY : utils.c.o

utils.i: utils.c.i
.PHONY : utils.i

# target to preprocess a source file
utils.c.i:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/utils.c.i
.PHONY : utils.c.i

utils.s: utils.c.s
.PHONY : utils.s

# target to generate assembly for a file
utils.c.s:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/utils.c.s
.PHONY : utils.c.s

variable.o: variable.c.o
.PHONY : variable.o

# target to build an object file
variable.c.o:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/variable.c.o
.PHONY : variable.c.o

variable.i: variable.c.i
.PHONY : variable.i

# target to preprocess a source file
variable.c.i:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/variable.c.i
.PHONY : variable.c.i

variable.s: variable.c.s
.PHONY : variable.s

# target to generate assembly for a file
variable.c.s:
	$(MAKE) -f CMakeFiles/kiscript.dir/build.make CMakeFiles/kiscript.dir/variable.c.s
.PHONY : variable.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... kiscript"
	@echo "... rebuild_cache"
	@echo "... activation_record.o"
	@echo "... activation_record.i"
	@echo "... activation_record.s"
	@echo "... expression_parser.o"
	@echo "... expression_parser.i"
	@echo "... expression_parser.s"
	@echo "... function_parser.o"
	@echo "... function_parser.i"
	@echo "... function_parser.s"
	@echo "... glib_utils.o"
	@echo "... glib_utils.i"
	@echo "... glib_utils.s"
	@echo "... interpreter.o"
	@echo "... interpreter.i"
	@echo "... interpreter.s"
	@echo "... lexical_parser.o"
	@echo "... lexical_parser.i"
	@echo "... lexical_parser.s"
	@echo "... lexical_parser_utils.o"
	@echo "... lexical_parser_utils.i"
	@echo "... lexical_parser_utils.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... module_tests.o"
	@echo "... module_tests.i"
	@echo "... module_tests.s"
	@echo "... parser.o"
	@echo "... parser.i"
	@echo "... parser.s"
	@echo "... program_parser.o"
	@echo "... program_parser.i"
	@echo "... program_parser.s"
	@echo "... statement_parser.o"
	@echo "... statement_parser.i"
	@echo "... statement_parser.s"
	@echo "... syntactic_parser.o"
	@echo "... syntactic_parser.i"
	@echo "... syntactic_parser.s"
	@echo "... syntactic_parser_utils.o"
	@echo "... syntactic_parser_utils.i"
	@echo "... syntactic_parser_utils.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
	@echo "... variable.o"
	@echo "... variable.i"
	@echo "... variable.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

